# Generated by Django 3.2 on 2021-04-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name': 'Ponto Turístico', 'verbose_name_plural': 'Pontos Turísticos'},
        ),
    ]
