# Generated by Django 3.2 on 2021-04-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210428_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
