# Generated by Django 3.2 on 2021-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('horario_funcionamento', models.TextField(verbose_name='Horário de Funcionamento')),
                ('idade_minima', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
            },
        ),
    ]
